enrich cronjob

diff --git a/cicd/manifests/cronjob.yaml b/cicd/manifests/cronjob.yaml
--- a/cicd/manifests/cronjob.yaml
+++ b/cicd/manifests/cronjob.yaml
@@ -37,84 +37,207 @@ spec:
             - |
               apt-get -qy update; apt-get -qy -o=Dpkg::Use-Pty=0 install curl jq
 
-              UNIXPENSE_API_URL=http://unixpense-svc-service.unixpense.svc.cluster.local:8000/api
-              FETCH_TRANSACTION_IDS_URL="$UNIXPENSE_API_URL/transactions/gmail/ids/last/20?skip_saved=true&skip_depth=10"
-              SAVE_TRANSACTIONS_URL="$UNIXPENSE_API_URL/transactions/gmail/save"
+              main() {
+                local UNIXPENSE_API_URL=http://unixpense-svc-service.unixpense.svc.cluster.local:8000/api
+                local FETCH_TRANSACTION_IDS_URL="$UNIXPENSE_API_URL/transactions/gmail/ids/last/20?skip_saved=true&skip_depth=10"
+                local SAVE_TRANSACTIONS_URL="$UNIXPENSE_API_URL/transactions/gmail/save"
+                local RESOLVE_TRANSACTIONS_URL="$UNIXPENSE_API_URL/transactions/gmail/resolve"
 
-              echo -n "- Resolving OAuth2 Access Token... "
+                echo -n "- Resolving OAuth2 Access Token... "
 
-              ACCESS_TOKEN_QUERY="\
-                SELECT access_token
-                FROM google_oauth2_tokens
-                WHERE user_email='$GMAIL_ADDRESS'"
+                local ACCESS_TOKEN="$(resolveAccessToken)"
 
-              ACCESS_TOKEN=$(mariadb unixpense \
-                -h mariadb-service.unixpense.svc.cluster.local \
-                -u$MARIADB_USER \
-                -p$MARIADB_PASSWORD \
-                -se "$ACCESS_TOKEN_QUERY")
+                echo -n "- Fetching new transaction IDs... "
 
-              echo $ACCESS_TOKEN
+                local FETCH_RESULT="$(fetchTransactionIds \"GET $FETCH_TRANSACTION_IDS_URL\" $ACCESS_TOKEN)"
+                
+                local FETCH_ERROR=$(echo $FETCH_RESULT | jq '.error')
 
-              echo -n "- Fetching new transaction IDs... "
+                if [ "$FETCH_ERROR" != null ]; then
+                  echo "Failed."
 
-              TRANSACTION_IDS=$(curl -s \
-                -X GET "$FETCH_TRANSACTION_IDS_URL" \
-                -H "Authorization: Bearer $ACCESS_TOKEN" \
-                -H "Accept: application/json")
+                  sendTelegram "$FETCH_ERROR"
 
-              TRANSACTION_ID_COUNT=$(echo $TRANSACTION_IDS | jq 'length')
+                  exit 1
+                fi
 
-              if [ "$TRANSACTION_ID_COUNT" -eq "0" ]; then
-                echo No new transactions.
+                local TRANSACTION_IDS="$(echo $FETCH_RESULT | jq '.result')"
 
-                exit
-              fi
+                local TRANSACTION_ID_COUNT=$(echo $TRANSACTION_IDS | jq 'length')
 
-              echo "Received $TRANSACTION_ID_COUNT new transaction(s)."
+                if [ "$TRANSACTION_ID_COUNT" -eq "0" ]; then
+                  echo "No new transactions."
 
-              echo -n "- Saving new transaction IDs... "
+                  exit
+                fi
 
-              RESULT=$(curl -s \
-                -X POST "$SAVE_TRANSACTIONS_URL" \
-                -H "Authorization: Bearer $ACCESS_TOKEN" \
-                -H "Accept: application/json" \
-                -H "Content-Type: application/json" \
-                -d $TRANSACTION_IDS)
+                echo "Received $TRANSACTION_ID_COUNT new transaction(s)."
 
-              RESULT_MESSAGE=$(echo $RESULT | jq '.message')
-              RESULT_ERROR=$(echo $RESULT | jq '.error')
-              TELEGRAM_MESSAGE=""
+                # Hydrate access token, in case the first request triggered a token refresh
+                ACCESS_TOKEN="$(resolveAccessToken)"
 
-              if [ "$RESULT_MESSAGE" != null ]; then
-                echo Success: $RESULT_MESSAGE
+                echo -n "- Saving new transaction IDs... "
 
-                TELEGRAM_MESSAGE=$RESULT_MESSAGE
-              elif [ "$RESULT_ERROR" != null ]; then
-                echo Failed: $RESULT_ERROR
+                local SAVE_RESULT="$(saveTransactions \"POST $SAVE_TRANSACTIONS_URL\" $ACCESS_TOKEN \"$TRANSACTION_IDS\")"
+                
+                local SAVE_ERROR=$(echo $SAVE_RESULT | jq '.error')
 
-                TELEGRAM_MESSAGE=$RESULT_ERROR
-              else
-                echo Unexpected result: $RESULT
+                if [ "$SAVE_ERROR" != null ]; then
+                  echo "Failed."
 
-                TELEGRAM_MESSAGE=$RESULT
-              fi
+                  sendTelegram "$SAVE_ERROR"
 
-              echo -n "- Sending result to Telegram... "
+                  exit 1
+                fi
 
-              TELEGRAM_API_RESULT=$(curl -s \
-                -X POST https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage \
-                -H 'Content-Type: application/json' \
-                -d "{\"chat_id\": \"$TELEGRAM_CHAT_ID\", \"text\": $TELEGRAM_MESSAGE, \"disable_notification\": true}")
+                local SAVE_MESSAGE="$(SAVE_RESULT | jq '.result')."
 
-              TELEGRAM_API_SUCCESSFUL=$(echo $TELEGRAM_API_RESULT | jq '.ok')
+                echo "$SAVE_MESSAGE"
 
-              if [ "$TELEGRAM_API_RESULT" -eq "false" ]; then
-                TELEGRAM_API_ERROR_DESCRIPTION=$(echo $TELEGRAM_API_RESULT | jq '.description')
+                sendTelegram "$SAVE_MESSAGE"
 
-                echo "Failed: $TELEGRAM_API_ERROR_DESCRIPTION"
+                echo -n "- Resolving transactions... "
 
-                exit
-              fi
+                local RESOLVE_RESULT="$(resolveTransactions \"POST $RESOLVE_TRANSACTIONS_URL\" $ACCESS_TOKEN \"$TRANSACTION_IDS\")"
+                
+                local RESOLVE_ERROR=$(echo $RESOLVE_RESULT | jq '.error')
 
-              echo Success
+                if [ "$RESOLVE_ERROR" != null ]; then
+                  echo "Failed."
+
+                  sendTelegram "$RESOLVE_ERROR"
+
+                  exit 1
+                fi
+
+                local $RESOLVE_MESSAGE=$(RESOLVE_RESULT | jq '.result')
+
+                echo "Success."
+
+                sendTelegram "<code>$RESOLVE_MESSAGE</code>"
+              }
+
+              resolveAccessToken() {
+                local ACCESS_TOKEN_QUERY="\
+                  SELECT access_token
+                  FROM google_oauth2_tokens
+                  WHERE user_email='$GMAIL_ADDRESS'"
+
+                local ACCESS_TOKEN=$(mariadb unixpense \
+                  -h mariadb-service.unixpense.svc.cluster.local \
+                  -u$MARIADB_USER \
+                  -p$MARIADB_PASSWORD \
+                  -se "$ACCESS_TOKEN_QUERY")
+
+                echo $ACCESS_TOKEN
+              }
+
+              fetchTransactionIds() {
+                if [[ $# -ne 2 ]]; then
+                    echo "fetchTransactionIds(): called with $# parameters, expected 2"
+
+                    exit 1
+                fi
+
+                local REQUEST="$1"
+                local ACCESS_TOKEN=$2
+
+                local RESULT=$(curl -s \
+                  -X "$REQUEST" \
+                  -H "Authorization: Bearer $ACCESS_TOKEN" \
+                  -H "Accept: application/json")
+
+                echo "$(formatResult \"$RESULT\")"
+              }
+              
+              saveTransactions() {
+                if [[ $# -ne 3 ]]; then
+                    echo "saveTransactions(): called with $# parameters, expected 3"
+
+                    exit 1
+                fi
+
+                local REQUEST="$1"
+                local ACCESS_TOKEN=$2
+                local TRANSACTION_IDS="$3"
+
+                local RESULT=$(curl -s \
+                  -X "$REQUEST" \
+                  -H "Authorization: Bearer $ACCESS_TOKEN" \
+                  -H "Accept: application/json" \
+                  -H "Content-Type: application/json" \
+                  -d \"$TRANSACTION_IDS\")
+
+                echo "$(formatResult \"$RESULT\")"
+              }
+
+              resolveTransactions() {
+                if [[ $# -ne 3 ]]; then
+                    echo "resolveTransactions(): called with $# parameters, expected 3"
+
+                    exit 1
+                fi
+
+                local REQUEST="$1"
+                local ACCESS_TOKEN=$2
+                local TRANSACTION_IDS="$3"
+
+                local RESULT=$(curl -s \
+                  -X "$REQUEST" \
+                  -H "Authorization: Bearer $ACCESS_TOKEN" \
+                  -H "Accept: application/json" \
+                  -H "Content-Type: application/json" \
+                  -d \"$TRANSACTION_IDS\")
+
+                echo "$(formatResult \"$RESULT\")"
+              }
+
+              formatResult() {
+                if [[ $# -ne 1 ]]; then
+                    echo "formatResult(): called with $# parameters, expected 1"
+
+                    exit 1
+                fi
+
+                local RESULT_RAW=$1
+
+                local RESULT_MESSAGE=$(echo $RESULT_RAW | jq '.message')
+                local RESULT_ERROR=$(echo $RESULT_RAW | jq '.error')
+
+                if [ "$RESULT_MESSAGE" != null ]; then
+                  echo "{\"result\": \"<b><u>Success:</u> <i>$RESULT_MESSAGE</i></b>\"}"
+                elif [ "$RESULT_ERROR" != null ]; then
+                  echo "{\"error\": \"<b><u>Error:</u> <i>$RESULT_ERROR</i></b>\"}"
+                else
+                  echo "{\"result\": \"$RESULT_RAW\"}"
+                fi
+              }
+              
+              function sendTelegram() {
+                if [[ $# -ne 1 ]]; then
+                    echo "sendTelegram(): called with $# parameters, expected 1"
+
+                    exit 1
+                fi
+
+                local MESSAGE="$1"
+
+                TELEGRAM_API_RESULT=$(curl -s \
+                  -X POST https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage \
+                  -H 'Content-Type: application/json' \
+                  -d "{\"chat_id\": \"$TELEGRAM_CHAT_ID\", \"parse_mode\": \"HTML\", \"text\": $MESSAGE, \"disable_notification\": true}")
+
+                TELEGRAM_API_SUCCESSFUL=$(echo $TELEGRAM_API_RESULT | jq '.ok')
+
+                if [ "$TELEGRAM_API_SUCCESSFUL" -eq "false" ]; then
+                  TELEGRAM_API_ERROR_DESCRIPTION=$(echo $TELEGRAM_API_RESULT | jq '.description')
+
+                  echo "Failed: $TELEGRAM_API_ERROR_DESCRIPTION"
+
+                  exit 1
+                fi
+
+                echo "Success: $(echo \"$TELEGRAM_API_RESULT | jq '.result')\""
+              }
+
+              main
